# Generated by Django 4.2.2 on 2023-06-16 12:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('machine_id', models.CharField(max_length=150)),
                ('machine_location', models.CharField(max_length=250)),
                ('digital_input', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None)),
                ('digital_output', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None)),
                ('analog_input', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=10), size=None)),
                ('analog_output', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=10), size=None)),
            ],
            options={
                'db_table': 'machine_schema"."machinedetails_table',
            },
        ),
    ]
